language: node_js

cache:
  npm: false

node_js:
  - "12"
  - "10"
  - "8"
  - "6"

script:
  - npm run lint && npm run coveralls -- -c

notifications:
  email:
    on_success: never
    on_failure: always
